(function(b){b.fn.tile=function(e){var a,d,c,f,h=this.length-1,g;e||(e=this.length);this.each(function(){g=this.style;g.removeProperty&&g.removeProperty("height");g.removeAttribute&&g.removeAttribute("height")});return this.each(function(g){c=g%e;0==c&&(a=[]);a[c]=b(this);f=a[c].height();if(0==c||f>d)d=f;(g==h||c==e-1)&&b.each(a,function(){this.height(d)})})}})(jQuery);
!function(b){var e=function(a,b){this.init("tooltip",a,b)};e.prototype={constructor:e,init:function(a,d,c){this.type=a;this.$element=b(d);this.options=this.getOptions(c);this.enabled=!0;"manual"!=this.options.trigger&&(a="hover"==this.options.trigger?"mouseenter":"focus",d="hover"==this.options.trigger?"mouseleave":"blur",this.$element.on(a,this.options.selector,b.proxy(this.enter,this)),this.$element.on(d,this.options.selector,b.proxy(this.leave,this)));this.options.selector?this._options=b.extend({},
this.options,{trigger:"manual",selector:""}):this.fixTitle()},getOptions:function(a){a=b.extend({},b.fn[this.type].defaults,a,this.$element.data());a.delay&&"number"==typeof a.delay&&(a.delay={show:a.delay,hide:a.delay});return a},enter:function(a){var d=b(a.currentTarget)[this.type](this._options).data(this.type);if(!d.options.delay||!d.options.delay.show)return d.show();clearTimeout(this.timeout);d.hoverState="in";this.timeout=setTimeout(function(){"in"==d.hoverState&&d.show()},d.options.delay.show)},
leave:function(a){var d=b(a.currentTarget)[this.type](this._options).data(this.type);this.timeout&&clearTimeout(this.timeout);if(!d.options.delay||!d.options.delay.hide)return d.hide();d.hoverState="out";this.timeout=setTimeout(function(){"out"==d.hoverState&&d.hide()},d.options.delay.hide)},show:function(){var a,b,c,f,h,g,e;if(this.hasContent()&&this.enabled){a=this.tip();this.setContent();this.options.animation&&a.addClass("fade");g="function"==typeof this.options.placement?this.options.placement.call(this,
a[0],this.$element[0]):this.options.placement;b=/in/.test(g);a.remove().css({top:0,left:0,display:"block"}).appendTo(b?this.$element:document.body);c=this.getPosition(b);f=a[0].offsetWidth;h=a[0].offsetHeight;switch(b?g.split(" ")[1]:g){case "bottom":e={top:c.top+c.height,left:c.left+c.width/2-f/2};break;case "top":e={top:c.top-h,left:c.left+c.width/2-f/2};break;case "left":e={top:c.top+c.height/2-h/2,left:c.left-f};break;case "right":e={top:c.top+c.height/2-h/2,left:c.left+c.width}}a.css(e).addClass(g).addClass("in")}},
isHTML:function(a){return"string"!=typeof a||"<"===a.charAt(0)&&">"===a.charAt(a.length-1)&&3<=a.length||/^(?:[^<]*<[\w\W]+>[^>]*$)/.exec(a)},setContent:function(){var a=this.tip(),b=this.getTitle();a.find(".tooltip-inner")[this.isHTML(b)?"html":"text"](b);a.removeClass("fade in top bottom left right")},hide:function(){var a=this.tip();a.removeClass("in");if(b.support.transition&&this.$tip.hasClass("fade")){var d=setTimeout(function(){a.off(b.support.transition.end).remove()},500);a.one(b.support.transition.end,
function(){clearTimeout(d);a.remove()})}else a.remove()},fixTitle:function(){var a=this.$element;if(a.attr("title")||"string"!=typeof a.attr("data-original-title"))a.attr("data-original-title",a.attr("title")||"").removeAttr("title")},hasContent:function(){return this.getTitle()},getPosition:function(a){return b.extend({},a?{top:0,left:0}:this.$element.offset(),{width:this.$element[0].offsetWidth,height:this.$element[0].offsetHeight})},getTitle:function(){var a=this.$element,b=this.options;return a.attr("data-original-title")||
("function"==typeof b.title?b.title.call(a[0]):b.title)},tip:function(){return this.$tip=this.$tip||b(this.options.template)},validate:function(){this.$element[0].parentNode||(this.hide(),this.options=this.$element=null)},enable:function(){this.enabled=!0},disable:function(){this.enabled=!1},toggleEnabled:function(){this.enabled=!this.enabled},toggle:function(){this[this.tip().hasClass("in")?"hide":"show"]()}};b.fn.tooltip=function(a){return this.each(function(){var d=b(this),c=d.data("tooltip"),
f="object"==typeof a&&a;c||d.data("tooltip",c=new e(this,f));if("string"==typeof a)c[a]()})};b.fn.tooltip.Constructor=e;b.fn.tooltip.defaults={animation:!0,placement:"top",selector:!1,template:'<div class="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>',trigger:"hover",title:"",delay:0}}(window.jQuery);
!function(b){var e=function(a,b){this.init("popover",a,b)};e.prototype=b.extend({},b.fn.tooltip.Constructor.prototype,{constructor:e,setContent:function(){var a=this.tip(),b=this.getTitle(),c=this.getContent();a.find(".popover-title")[this.isHTML(b)?"html":"text"](b);a.find(".popover-content > *")[this.isHTML(c)?"html":"text"](c);a.removeClass("fade top bottom left right in")},hasContent:function(){return this.getTitle()||this.getContent()},getContent:function(){var a=this.$element,b=this.options;
return a.attr("data-content")||("function"==typeof b.content?b.content.call(a[0]):b.content)},tip:function(){this.$tip||(this.$tip=b(this.options.template));return this.$tip}});b.fn.popover=function(a){return this.each(function(){var d=b(this),c=d.data("popover"),f="object"==typeof a&&a;c||d.data("popover",c=new e(this,f));if("string"==typeof a)c[a]()})};b.fn.popover.Constructor=e;b.fn.popover.defaults=b.extend({},b.fn.tooltip.defaults,{placement:"right",content:"",template:'<div class="popover"><div class="arrow"></div><div class="popover-inner"><h3 class="popover-title"></h3><div class="popover-content"><p class="inner"></p></div></div></div>'})}(window.jQuery);
!function(b){var e=function(a,d){this.$element=b(a);this.options=b.extend({},b.fn.button.defaults,d)};e.prototype.setState=function(a){var b=this.$element,c=b.data(),e=b.is("input")?"val":"html";a+="Text";c.resetText||b.data("resetText",b[e]());b[e](c[a]||this.options[a]);setTimeout(function(){"loadingText"==a?b.addClass("disabled").attr("disabled","disabled"):b.removeClass("disabled").removeAttr("disabled")},0)};e.prototype.toggle=function(){var a=this.$element.parent('[data-toggle="buttons-radio"]');
a&&a.find(".active").removeClass("active");this.$element.toggleClass("active")};b.fn.button=function(a){return this.each(function(){var d=b(this),c=d.data("button"),f="object"==typeof a&&a;c||d.data("button",c=new e(this,f));"toggle"==a?c.toggle():a&&c.setState(a)})};b.fn.button.defaults={loadingText:"loading..."};b.fn.button.Constructor=e;b(function(){b("body").on("click.button.data-api","[data-toggle^=button]",function(a){a=b(a.target);a.hasClass("btn")||(a=a.closest(".btn"));a.button("toggle")})})}(window.jQuery);
!function(b){function e(){this.$element.hide().trigger("hidden");a.call(this)}function a(a){var c=this.$element.hasClass("fade")?"fade":"";if(this.isShown&&this.options.backdrop){var e=b.support.transition&&c;this.$backdrop=b('<div class="modal-backdrop '+c+'" />').appendTo(document.body);"static"!=this.options.backdrop&&this.$backdrop.click(b.proxy(this.hide,this));e&&this.$backdrop[0].offsetWidth;this.$backdrop.addClass("in");e?this.$backdrop.one(b.support.transition.end,a):a()}else!this.isShown&&
this.$backdrop?(this.$backdrop.removeClass("in"),b.support.transition&&this.$element.hasClass("fade")?this.$backdrop.one(b.support.transition.end,b.proxy(d,this)):d.call(this)):a&&a()}function d(){this.$backdrop.remove();this.$backdrop=null}function c(){var a=this;if(this.isShown&&this.options.keyboard)b(document).on("keyup.dismiss.modal",function(b){27==b.which&&a.hide()});else this.isShown||b(document).off("keyup.dismiss.modal")}var f=function(a,c){this.options=c;this.$element=b(a).delegate('[data-dismiss="modal"]',
"click.dismiss.modal",b.proxy(this.hide,this))};f.prototype={constructor:f,toggle:function(){return this[!this.isShown?"show":"hide"]()},show:function(){var d=this,e=b.Event("show");this.$element.trigger(e);!this.isShown&&!e.isDefaultPrevented()&&(b("body").addClass("modal-open"),this.isShown=!0,c.call(this),a.call(this,function(){var a=b.support.transition&&d.$element.hasClass("fade");d.$element.parent().length||d.$element.appendTo(document.body);d.$element.show();a&&d.$element[0].offsetWidth;d.$element.addClass("in");
a?d.$element.one(b.support.transition.end,function(){d.$element.trigger("shown")}):d.$element.trigger("shown")}),d.$element.css({top:b(window).scrollTop()+80}),e=10,b(document).width()-d.$element.width()>2*e&&(e=(b(document).width()-d.$element.width())/2),d.$element.css({left:e}),this.$backdrop.css({height:b(document).height()}))},hide:function(a){a&&a.preventDefault();a=b.Event("hide");this.$element.trigger(a);if(this.isShown&&!a.isDefaultPrevented())if(this.isShown=!1,b("body").removeClass("modal-open"),
c.call(this),this.$element.removeClass("in"),b.support.transition&&this.$element.hasClass("fade")){var d=this,f=setTimeout(function(){d.$element.off(b.support.transition.end);e.call(d)},500);this.$element.one(b.support.transition.end,function(){clearTimeout(f);e.call(d)})}else e.call(this)}};b.fn.modal=function(a){return this.each(function(){var c=b(this),d=c.data("modal"),e=b.extend({},b.fn.modal.defaults,c.data(),"object"==typeof a&&a);d||c.data("modal",d=new f(this,e));if("string"==typeof a)d[a]();
else e.show&&d.show()})};b.fn.modal.defaults={backdrop:!0,keyboard:!0,show:!0};b.fn.modal.Constructor=f;b(function(){b("body").on("click.modal.data-api",'[data-toggle="modal"]',function(a){var c=b(this),d,e=b(c.attr("data-target")||(d=c.attr("href"))&&d.replace(/.*(?=#[^\s]+$)/,"")),c=e.data("modal")?"toggle":b.extend({},e.data(),c.data());a.preventDefault();e.modal(c)})})}(window.jQuery);
!function(b){var e=function(a){this.element=b(a)};e.prototype={constructor:e,show:function(){var a=this.element,d=a.closest("ul:not(.dropdown-menu)"),c=a.attr("data-target"),e,h;c||(c=(c=a.attr("href"))&&c.replace(/.*(?=#[^\s]*$)/,""));a.parent("li").hasClass("active")||(e=d.find(".active a").last()[0],h=b.Event("show",{relatedTarget:e}),a.trigger(h),h.isDefaultPrevented()||(c=b(c),this.activate(a.parent("li"),d),this.activate(c,c.parent(),function(){a.trigger({type:"shown",relatedTarget:e})})))},
activate:function(a,d,c){function e(){h.removeClass("active").find("> .dropdown-menu > .active").removeClass("active");a.addClass("active");g?(a[0].offsetWidth,a.addClass("in")):a.removeClass("fade");a.parent(".dropdown-menu")&&a.closest("li.dropdown").addClass("active");c&&c()}var h=d.find("> .active"),g=c&&b.support.transition&&h.hasClass("fade");g?h.one(b.support.transition.end,e):e();h.removeClass("in")}};b.fn.tab=function(a){return this.each(function(){var d=b(this),c=d.data("tab");c||d.data("tab",
c=new e(this));if("string"==typeof a)c[a]()})};b.fn.tab.Constructor=e;b(function(){b("body").on("click.tab.data-api",'[data-toggle="tab"], [data-toggle="pill"]',function(a){a.preventDefault();b(this).tab("show")})})}(window.jQuery);
